name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install APT dependencies (cached)
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: g++-14 cmake libboost-all-dev build-essential ccache
        version: 1.0

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ runner.os }}-gcc14-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ccache-${{ runner.os }}-gcc14-
          ccache-${{ runner.os }}-

    - name: Build (CMake + ccache)
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build -j2

    - name: Test
      run: |
        ./scripts/test-runner.sh