name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-14 cmake libboost-all-dev
        
    - name: Build project
      run: |
        make clean
        make
        
    - name: Run tests
      run: |
        chmod +x scripts/test-runner.sh
        make test
        
    - name: Build with CMake
      run: |
        mkdir -p build
        cmake -S . -B build
        cmake --build build
        
    - name: Test CMake build
      run: |
        cd build
        ../scripts/test-runner.sh 