name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-14 cmake libboost-all-dev
        
    - name: Build and test with CMake
      run: |
        mkdir -p build
        cmake -S . -B build -DCMAKE_CXX_STANDARD=23
        cmake --build build
        chmod +x scripts/test-runner.sh
        cd build
        ../scripts/test-runner.sh 